[start]
# cmd = "php -S 0.0.0.0:$PORT index.php" 
# Commented out to let Nixpacks use default Nginx/Apache which is production ready

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --ignore-platform-reqs"
]
